files:
    -
        source_path: "file.txt"
    -
        multilingual_path: "/dir/*.txt"
    -
        source_path: '/HelloWorld/en.lproj/*.strings'
        translation_path: '/HelloWorld/[locale].lproj/[filename].strings'
        options:
              fill_untranslated_keys_with_source_text: true
    -
        translation_path: "/dir/[locale]/[filename].txt"
